server:
  port: 80
spring:
  application:
    name: api-gateway
  redis:
    host: 192.168.200.128
    port: 6379
    database: 0
    timeout: 1800000
    password:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.128:8848
    gateway:
      discovery:      #是否与服务发现组件进行结合，通过 serviceId(必须设置成大写) 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
        locator:      #路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问。
          enabled: true
      routes:
        - id: service-product # 唯一标识
          uri: lb://service-product # 负载均衡服务
          predicates:
            - Path=/*/product/** # 路径匹配
        - id: service-item # 唯一标识
          uri: lb://service-item # 负载均衡服务
          predicates:
            - Path=/*/item/** # 路径匹配
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/*/user/**
        - id: service-list
          uri: lb://service-list
          predicates:
            - Path=/*/list/**
        - id: service-cart
          uri: lb://service-cart
          predicates:
            - Path=/*/cart/**
        - id: service-order
          uri: lb://service-order
          predicates:
            - Path=/*/order/**
        - id: service-payment
          uri: lb://service-payment
          predicates:
            - Path=/*/payment/**
        - id: service-activity
          uri: lb://service-activity
          predicates:
            - Path=/*/activity/** # 路径匹配
          filters:
            - name: RequestRateLimiter #filter名称必须是RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2 #允许用户每秒处理多少个请求
                redis-rate-limiter.burstCapacity: 2 #令牌桶的容量，允许在一秒钟内完成的最大请求数
                key-resolver: "#{@ipKeyResolver}" # 遵循哪个限流规则！
        #==================web前端==========================
        - id: web-item  # 唯一标识
          uri: lb://web-all # 负载均衡服务
          predicates:
            - Host=item.gmall.com # 映射域名
        - id: web-index  # 唯一标识
          uri: lb://web-all # 负载均衡服务
          predicates:
            - Host=www.gmall.com # 映射域名
        - id: web-list  # 唯一标识
          uri: lb://web-all # 负载均衡服务
          predicates:
            - Host=list.gmall.com # 映射域名
        - id: web-passport
          uri: lb://web-all
          predicates:
            - Host=passport.gmall.com
        - id: web-passport
          uri: lb://web-all
          predicates:
            - Host=cart.gmall.com
        - id: web-order
          uri: lb://web-all
          predicates:
            - Host=order.gmall.com
        - id: web-payment
          uri: lb://web-all
          predicates:
            - Host=payment.gmall.com
        - id: web-activity
          uri: lb://web-all
          predicates:
            - Host=activity.gmall.com
authUrls:
  url: trade.html,myOrder.html #,list.html 配黑名单用户访问上述控制器时，需要登录。